#!/usr/bin/env bash
# cayn build_tier <TIER> <FONT> — assemble one training tier by symlinking the
# medical + annotated pool PNGs into a single folder and merging their labels.
# Prints the tier folder path on stdout.
#
# Pools are generated by generate_pool_set.sh into (via the ~/cayn/data symlink):
#   $AUGB = data/processed/synthetic_samples/augmented_images/aug_<corpus>_<size>_<font>_<DATE>/
#   $LBLB = data/processed/synthetic_samples/img_labels/labels_<corpus>_<size>_<font>_<DATE>/labels.json
# Tier sizes (spec §6.5.21): T2=med12k+anno9k  T3=med36k+anno27k  T4=med120k+anno90k
set -euo pipefail
source "$(dirname "$0")/env.sh"
TIER="$1"; FONT="$2"   # FONT = 1font | mf
case "$TIER" in
  T1) MED=4k; ANNO=3k ;;
  T2) MED=12k; ANNO=9k ;;
  T3) MED=36k; ANNO=27k ;;
  T4) MED=120k; ANNO=90k ;;
  *) echo "unknown tier '$TIER'" >&2; exit 1 ;;
esac

AUGB="$PROJECT_ROOT/data/processed/synthetic_samples/augmented_images"
LBLB="$PROJECT_ROOT/data/processed/synthetic_samples/img_labels"
OUT="$WS/pools/aug_${TIER}_${FONT}"
if [ -f "$OUT/labels.json" ]; then echo "$OUT"; exit 0; fi   # already assembled

med_dir=$(ls -d "$AUGB"/aug_medical_${MED}_${FONT}_* 2>/dev/null | head -1)
anno_dir=$(ls -d "$AUGB"/aug_anno_${ANNO}_${FONT}_* 2>/dev/null | head -1)
med_lbl=$(ls "$LBLB"/labels_medical_${MED}_${FONT}_*/labels.json 2>/dev/null | head -1)
anno_lbl=$(ls "$LBLB"/labels_anno_${ANNO}_${FONT}_*/labels.json 2>/dev/null | head -1)
[ -d "$med_dir" ] && [ -d "$anno_dir" ] && [ -f "$med_lbl" ] && [ -f "$anno_lbl" ] || {
  echo "missing pools/labels for $TIER $FONT:" >&2
  echo "  med=$med_dir anno=$anno_dir" >&2
  echo "  med_lbl=$med_lbl anno_lbl=$anno_lbl" >&2
  exit 1
}

mkdir -p "$OUT"
# batched symlink so the 120k/90k tiers don't blow ARG_MAX
find "$med_dir" "$anno_dir" -maxdepth 1 -name '*.png' -print0 | xargs -0 ln -sft "$OUT"
# merge labels (disjoint stems -> union, no collisions)
python - "$med_lbl" "$anno_lbl" "$OUT/labels.json" <<'PY'
import json, sys
m = json.load(open(sys.argv[1], encoding="utf-8"))
m.update(json.load(open(sys.argv[2], encoding="utf-8")))
json.dump(m, open(sys.argv[3], "w", encoding="utf-8"), ensure_ascii=False)
PY
echo "$OUT"
